name: securewave_app
version: 4.0.0+1
publish_to: 'none'

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  dio: ^5.4.3
  flutter_secure_storage: ^9.2.2
  go_router: ^14.2.0
  intl: ^0.19.0
  uuid: ^4.4.0
  connectivity_plus: ^6.0.3
  platform_info: ^4.0.2
  flutter_spinkit: ^5.2.1
  flutter_svg: ^2.0.10+1
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/icon.png
  remove_alpha_ios: true
  macos:
    generate: true
  windows:
    generate: true
    icon_size: 256
  linux:
    generate: true
